auto: true
title: WeiweiWeb
name: WeiweiWeb
permalink: pretty
exclude: README.md

category_dir: ''
category_title_prefix: ''

url: http://weiweiweb.org
author :
  name : Ai Weiwei
  github : aiweiwei
  twitter : aiww
  
languages :
  en: English
  zh: 中文
