auto: true
title: Ai Weiwei
permalink: pretty
exclude: README.md

keywords: ['Ai Weiwei', 'art', 'china', 'beijing']

category_dir: ''
category_title_prefix: ''

url: http://weiweiweb.org
author :
  name : Ai Weiwei
  github : aiweiwei
  twitter : aiww
  
languages :
  en: English
  zh: 中文
